[project]
name = "cistercian-num"
version = "0.1.0"
description = "Train models to read Cistercian numbers"
readme = "README.md"
authors = [
    { name = "dstilesr" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3,<4",
    "numpy>=2,<3",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.6.3",
    "pytest>=9,<10",
]

[tool.uv.workspace]
members = [
    "packages/data_utils",
    "packages/models",
    "packages/visualise",
]

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"
